baseURL       = "https://ripplestud.io/"
languageCode  = "en-ca"
title         = "Ripple Studio | Recording Studio"
theme         = ["roxo", "plausible-hugo"]
summarylength = 25

# Plausible submodule
[module]
[[module.imports]]
  path = "github.com/divinerites/plausible-hugo"

# Plausible Analytics
[params.plausible]
  enable = true
  domain = "ripplestud.io"
  proxy_netlify = true
  dash_link = "https://plausible.io/share/yourdomain?auth=AZE1234RTYUOP67"
  dash_theme = "dark"
  dash_bgcolor = "transparent"
  public_dashboard = true
  gitstar = false

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Listen"
    url     = "music"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Ripple Studio | Recording studio serving the Greater Ottawa region"
  author = "Ripple Studio"
  # Google Analitycs
  # googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First name"
    placeholder_last_name         = "Last name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project type"
    placeholder_about_the_project = "About the project"
    send_message                  = "Send message"

    [[params.contactForm.projectType]]
      value = "rec"
      title  = "Recording"
    [[params.contactForm.projectType]]
      value = "mm"
      title  = "Mixing/Mastering"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "AUDIO ENGINEERING WITH SOUL"
    tagline               = "Shaping your vision into an engaging story"
    primary_button        = "Listen"
    primary_button_url    = "music"
    secondary_button      = "Get in touch"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "LISTEN"
    subtitle  = "Making the world sound better one record at a time"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Contact"
    primary_button_url  = "contact"
    secondary_button    = "Not convinced"
    secondary_button_url = "music"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact"
      address = ""
      phone   = "514-577-5588"
      email   = "info@ripplestud.io"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Listen"
          url  = "music"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social media"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
        [[params.footer.social.link]]
          name = "SPCA"
          url  = "#"
        [[params.footer.social.link]]
          name = "Source code"
          url  = "https://gitlab.com/micgao/ripple"
        [[params.footer.social.link]]
          name = "Analytics"
          url  = "https://plausible.io/ripplestud.io"
      # Footer Service
      [params.footer.service]
        title       = "A word on privacy:"
        description = "We run a recording studio that is, above all, a passion project. We do not collect any personal data from this website's visitors nor do we use any cookies. There are thus no Privacy policy page or any cookie banner asking for your consent. Only the bare minimum metrics are kept track of, and by clicking the Analytics link on the left, you can get a full insight into exactly what we see. Right above, you will also find the full source code used to build this website. Commercial solutions are avoided as much as possible in favor of open source alternatives."