# NOTE TO SELF, REMEMBER TO CREDIT THEMES/ROXO SOMEWHERE ON THE WEBSITE

baseURL       = "https://ripplestud.io/"
languageCode  = "en-CA"
title         = "Ripple Studio | Recording Studio"
theme         = ["plausible-hugo"]
summarylength = 25

# Plausible Analytics
[params.plausible]
  enable = true
  domain = "ripplestud.io"
  gitstar = false

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Services"
    url     = "services"
    weight  = 2
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 3
  [[menu.nav]]
    name    = "Listen"
    url     = "music"
    weight  = 4
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 5
  [[menu.nav]]
    name    = "Contact"
    url     = "contact"
    weight  = 6

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Ripple Studio | Recording studio serving the Greater Ottawa region"
  author = "Ripple Studio"

  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Contact"
    url     = "contact"

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "AUDIO ENGINEERING WITH SOUL"
    tagline               = "Translating your vision into engaging stories"
    primary_button        = "Listen"
    primary_button_url    = "music"
    secondary_button      = "Contact"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "LISTEN"
    subtitle  = "Making the world sound better one record at a time"

  [params.call_to_action]
    enable              = true
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Contact"
    primary_button_url  = "contact"
    secondary_button    = "Not convinced"
    secondary_button_url = "music"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact"
      address = ""
      email   = "info@ripplestud.io"
      phone   = "(514) 577-5588"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Services"
          url  = "services"
        [[params.footer.sitemap.link]]
          name = "Music"
          url  = "music"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Links"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
        [[params.footer.social.link]]
          name = "SPCA"
          url  = "#"
        [[params.footer.social.link]]
          name = "Source code"
          url  = "https://gitlab.com/micgao/ripple"
        [[params.footer.social.link]]
          name = "Analytics"
          url  = "https://plausible.io/ripplestud.io"
      # Footer Service
      [params.footer.service]
        title       = "A word on privacy:"
        description = "We do not collect any personal data or other personally identifiable information, and there are no cookies on this website. The stats collected serve only to identify trends, and for the sake of transparency, they are fully open and can be accessed by clicking Analytics under Links."