baseURL       = "https://ripplestud.io/"
languageCode  = "en-ca"
title         = "Ripple Studio | Recording Studio"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Listen"
    url     = "music"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Ripple Studio | Recording studio serving the Greater Ottawa region"
  author = "Ripple Studio"
  # Google Analitycs
  # googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First name"
    placeholder_last_name         = "Last name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project type"
    placeholder_about_the_project = "About the project"
    send_message                  = "Send message"

    [[params.contactForm.projectType]]
      value = "rec"
      title  = "Recording"
    [[params.contactForm.projectType]]
      value = "mm"
      title  = "Mixing/Mastering"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Shaping your idea into an engaging story"
    tagline               = "AUDIO ENGINEERING WITH SOUL"
    primary_button        = "Listen"
    primary_button_url    = "music"
    secondary_button      = "Get in touch"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "LISTEN"
    subtitle  = "Making the world sound better one record at a time"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Contact"
    primary_button_url  = "contact"
    secondary_button    = "Not convinced"
    secondary_button_url = "music"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact"
      address = "1475 St-Charles Ouest, Longueuil, QC"
      phone   = "514-577-5588"
      email   = "info@ripplestud.io"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Listen"
          url  = "music"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "#"
        [[params.footer.social.link]]
          name = "SPCA"
          url  = "#"
        [[params.footer.social.link]]
          name = "Source code"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We help brands:"
        description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"