backend:
  name: gitlab
  repo: micgao/ripple # Path to your GitLab repository
  branch: main

publish_mode: editorial_workflow

media_folder: "static/images" # Media files will be stored in the repo under images/uploads
public_folder: "/images"